"""empty message

Revision ID: 41731c54ae1a
Revises: 
Create Date: 2019-02-22 17:18:58.598551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41731c54ae1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
